# Generated by Django 4.2.4 on 2024-10-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_article_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
