# Generated by Django 4.2.4 on 2024-10-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_videotranscript_remove_article_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperformance',
            name='watched_video_ids',
            field=models.TextField(blank=True, help_text='YouTube video IDs separated by semicolons', null=True),
        ),
        migrations.AlterField(
            model_name='userperformance',
            name='watched_videos',
            field=models.ManyToManyField(blank=True, to='directory.videoplayer'),
        ),
    ]
