# Generated by Django 4.2.4 on 2024-10-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_userperformance_watched_video_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_videos',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
